######################################################################
# Automatically generated by qmake (3.1) Wed Jun 29 23:00:48 2022
######################################################################

TEMPLATE = app
TARGET = Jr_TO-DO_PANEL
INCLUDEPATH += .

QT += core widgets network

HEADERS += \
    EntryDetail.h \
    EntryView.h \
    GroupDetail.h \
    GroupView.h \
    ListDetail.h \
    ListOrGroup.h \
    ListOrGroupDetail.h \
    ListView.h \
    SearchBar.h \
    SortableItem.h \
    data.h \
    entry.h \
    group.h \
    list.h \
    mainui.h \
    proxyEntry.h \
    proxyListOrGroup.h
SOURCES += main.cpp \
    EntryDetail.cpp \
    EntryView.cpp \
    GroupDetail.cpp \
    GroupView.cpp \
    ListDetail.cpp \
    ListView.cpp \
    SearchBar.cpp \
    data.cpp \
    json.cpp \
    list.cpp \
    mainui.cpp \
    proxyEntry.cpp \
    proxyListOrGroup.cpp
TRANSLATIONS += TO-DO_PANEL_zh_CN.ts

DISTFILES += \
    data.json
